name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
        coq-version:
          - 8.13.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

   #   - run: opam install ocamlformat.0.18.0
   #   - run: opam exec -- make fmt-check
      - run: opam install yojson
      - run: opam pin add coq ${{ matrix.coq-version }}
      - run: opam pin add coq-of-LLBC.dev . --no-action
      - run: opam depext conf-ruby --yes
      - run: opam install coq-of-LLBC --deps-only
      - run: opam install coq-of-LLBC --verbose
      - run: opam exec -- make coverage
      - run: opam exec -- bisect-ppx-report send-to Codecov