name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.13.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: git submodule update --init
      - run: opam pin add coq-of-LLBC.dev . --no-action
      - run: opam depext conf-ruby --yes
      - run: opam install coq-of-LLBC --deps-only
      - run: opam install coq-of-LLBC --verbose
      - run: dune build
